message("CPACK_TEMPORARY_INSTALL_DIRECTORY : ${CPACK_TEMPORARY_INSTALL_DIRECTORY}")
message("CMAKE_SOURCE_DIR : ${CMAKE_SOURCE_DIR}")
message("CMAKE_CURRENT_LIST_DIR/../../ : ${CMAKE_CURRENT_LIST_DIR}/../../")
message("CMAKE_CURRENT_LIST_DIR/generate-stubfiles.sh : ${CMAKE_CURRENT_LIST_DIR}/generate-stubfiles.sh")

execute_process(COMMAND bash "${CMAKE_CURRENT_LIST_DIR}/generate-stubfiles.sh" "${CMAKE_CURRENT_LIST_DIR}/../../" "${CPACK_TEMPORARY_INSTALL_DIRECTORY}" ${CMAKE_SYSTEM_NAME})


