name: Compile SOFA and run Tests
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  setup_build:
    runs-on: [self-hosted, sh-ubuntu]
    steps:
      - name: Clone SOFA and CI
        shell: bash
        run: |
          WORKSPACE=$(cat $GITHUB_WORKFLOW_SHA) 
          cd $WORKSPACE
          

          echo "Cloning SOFA at commit $GITHUB_WORKFLOW_SHA"
          mkdir $WORKSPACE/src && cd $WORKSPACE/src 
          SRC_DIR=$(pwd)

          git init
          git remote add origin https://www.github.com/$GITHUB_REPOSITORY_OWNER/sofa.git
          git fetch origin $GITHUB_WORKFLOW_SHA
          git checkout FETCH_HEAD

          cd $WORKSPACE


          echo "Cloning CI"
          mkdir $WORKSPACE/ci && cd $WORKSPACE/ci 
          CI_DIR=$(pwd)

          git init
          git remote add origin https://www.github.com/sofa-framework/ci.git
          git fetch origin master
          git checkout FETCH_HEAD

          cd $WORKSPACE


          mkdir build



