name: Compile SOFA and run Tests
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test_env:
    runs-on: [self-hosted, sh-ubuntu]
    steps:
      - name: Test env
        shell: bash
        run: |
          WORKSPACE=$(cat $GITHUB_WORKFLOW_SHA) 
          cd $WORKSPACE
          echo $(pwd)
          echo $WORKSPACE
